{
 "title": "IDP Decryption Errors",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   { "name": "TimePeriod", "query": "1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Ola test panel",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(verify_saml_hub_idp_validator_decryption_error_counter[5m]))"
    }
   ]
  },
  {
   "title": "[Staging ] Alerting IDP Response Decryption Errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (increase(verify_saml_hub_idp_validator_decryption_error_counter[10m]))",
     "legendFormat": "decryption errors"
    }
   ]
  },
  {
   "title": "IDP Response Decryption errors on $Datasource avg. over $TimePeriod",
   "type": "graph",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (entityId)(increase(verify_saml_hub_idp_validator_decryption_error_counter[$TimePeriod]))",
     "legendFormat": "{{entityId}}"
    }
   ]
  }
 ]
}