{
 "title": "Hub ECS Journeys",
 "tags": [ "verify" ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "timerange",
    "label": "Time Range",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Hub Journeys ops/min avg over $timerange",
   "type": "graph",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "60* sum without(instance)(rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageReceiverApi_handleRequestPost_count[$timerange]))",
     "legendFormat": "Users arriving from Govt. Service"
    },
    {
     "expr": "60*sum without(instance)(rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnRequestFromHub_count[$timerange]))",
     "legendFormat": "Users going to ID Provider"
    },
    {
     "expr": "60*sum without(instance)(rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageReceiverApi_handleResponsePost_count[$timerange]))",
     "legendFormat": "Users returning from ID Provider"
    },
    {
     "expr": "60* sum without(instance)(rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnResponseFromHub_count[$timerange]))",
     "legendFormat": "Users returning to Govt. Service"
    }
   ]
  },
  {
   "title": "Identities to GovServices p. $timerange",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum without(instance)(increase(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnResponseFromHub_count[$timerange]))"
    }
   ]
  },
  {
   "title": "🚨Alerts",
   "type": "graph",
   "description": "Slack alerts based on changes v. last week or month",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnRequestFromHub_count[1h])) / sum(rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageReceiverApi_handleRequestPost_count[1h]))) / (sum(rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageSenderApi_sendJsonAuthnRequestFromHub_count[1h] offset 30d)) / sum(rate(uk_gov_ida_hub_samlproxy_resources_SamlMessageReceiverApi_handleRequestPost_count[1h] offset 30d)))",
     "legendFormat": "egress rate to IdPS vs. 1 month ago"
    }
   ]
  },
  {
   "title": "Frontend Errors per $timerange",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(code) (increase(http_server_requests_total{code=~'[45]..'}[$timerange]))",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}