{
 "title": "Hub ECS",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Filters" },
   { "name": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "OCSP",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((verify_config_certificate_ocsp_revocation_status or verify_metadata_certificate_ocsp_success) == bool 0)"
    }
   ]
  },
  {
   "title": "Metadata expires in",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "verify_metadata_expiry/1000 - time()"
    }
   ]
  },
  {
   "title": "0 - 7 days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(((avg without(instance) (verify_config_certificate_expiry_date or verify_metadata_certificate_expiry) /1000 - time()) / 60 / 60 / 24) < bool 7)"
    }
   ]
  },
  {
   "title": "7 - 14 days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(((avg without(instance) (verify_config_certificate_expiry_date or verify_metadata_certificate_expiry)/1000 - time()) / 60 / 60 / 24) > 7 < bool 14)"
    }
   ]
  },
  {
   "title": "14 - 30 days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "\nsum(((avg without(instance)(verify_config_certificate_expiry_date or verify_metadata_certificate_expiry)/1000 - time()) / 60 / 60 / 24) > 14 < bool 30)"
    }
   ]
  },
  {
   "title": "30 - 60 days",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "\nsum(((avg without(instance) (verify_config_certificate_expiry_date or verify_metadata_certificate_expiry)/1000 - time()) / 60 / 60 / 24) > 30 < bool 60)"
    }
   ]
  },
  { "title": "All Alerts", "type": "alertlist", "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 } },
  {
   "title": "Certificate Expiries",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 2 },
   "targets": [
    {
     "expr": "avg (label_replace(verify_config_certificate_expiry_date or verify_metadata_certificate_expiry, \"cn\", \"$1\", \"subject\", \".*CN=([0-9A-Za-z_ ().-]+).*\")) without(use, instance, subject, job, timestamp, key_name) - time()*1000"
    }
   ]
  },
  {
   "title": "Matching Service Info",
   "type": "table-old",
   "description": "Details about healthy matching services",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg without (instance)(verify_saml_soap_proxy_msa_info\nand on (instance, job)\nverify_saml_soap_proxy_msa_health_status == 1)\n"
    }
   ]
  },
  {
   "title": "Java Heap Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "decbytes", "label": "Heap Memory Used" }
   ],
   "targets": [
    {
     "expr": "max(jvm_memory_bytes_used{area=\"heap\"}) without (instance)"
    }
   ]
  },
  {
   "title": "5xx responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "5xx responses per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(io_dropwizard_jetty_MutableServletContextHandler_5xx_responses_total[1m])) without (instance)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Utilisation Production",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percent", "label": "Memory Utilisation" }
   ],
   "targets": [
    {
     "alias": "Config Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-config-v2" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Egress Proxy Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-egress-proxy" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Frontend Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-frontend" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Analytics Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-analytics" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Metadata Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-metadata" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Policy Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-policy" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "SAML Engine Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-saml-engine" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "SAML Proxy Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-saml-proxy" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "SAML Soap Proxy Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-saml-soap-proxy" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Static Ingress HTTPS Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-static-ingress-https" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Static Ingress HTTP Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-static-ingress-http" },
     "metricName": "MemoryUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "2xx responses",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "2xx responses per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(io_dropwizard_jetty_MutableServletContextHandler_2xx_responses_total[1m])) without (instance)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Utilisation Production",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent", "label": "CPU Utilisation" }
   ],
   "targets": [
    {
     "alias": "Config Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-config-v2" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Egress Proxy Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-egress-proxy" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Frontend Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-frontend" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Analytics Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-analytics" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Metadata Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-metadata" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Policy Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-policy" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "SAML Engine Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-saml-engine" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "SAML Proxy Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-saml-proxy" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "SAML Soap Proxy Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-saml-soap-proxy" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Static Ingress HTTPS Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-static-ingress-https" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Static Ingress HTTP Task",
     "dimensions": { "ClusterName": "prod", "ServiceName": "prod-static-ingress-http" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ECS",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "EC2 Memory Free Space",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "node_memory_MemAvailable / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Matching Service Health Status History",
   "type": "graph",
   "description": "Details about healthy matching services",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg without (job, instance)(verify_saml_soap_proxy_msa_health_status)",
     "legendFormat": "{{matchingService}}"
    }
   ]
  },
  {
   "title": "Matching Service Health Status",
   "type": "table-old",
   "description": "Details about healthy matching services",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "avg without (job, instance)(verify_saml_soap_proxy_msa_health_status)",
     "legendFormat": "{{matchingService}}"
    }
   ]
  }
 ]
}