{
 "title": "Ticket Type Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "[Joint] Instances needing reboot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_reboot_required" }
   ]
  },
  {
   "title": "[Staging] Instances needing reboot",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_reboot_required" }
   ]
  },
  {
   "title": "[Joint] NTP Time Drift",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_ntp_offset_seconds" }
   ]
  },
  {
   "title": "[Staging] NTP Time Drift",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_ntp_offset_seconds" }
   ]
  },
  {
   "title": "[Joint] Disk Predicted to Fill Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_avail{fstype!=\"squashfs\",mountpoint!=\"/snap/core/6130\",mountpoint!=\"/snap/amazon-ssm-agent/930\",mountpoint!=\"/var/lib/lxcfs\"}[12h], 3 * 86400) and on (instance) (time() - node_creation_time) > 3600"
    }
   ]
  },
  {
   "title": "[Staging] Disk Predicted to Fill Alert",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "predict_linear(node_filesystem_avail{fstype!=\"squashfs\",mountpoint!=\"/snap/core/6130\",mountpoint!=\"/snap/amazon-ssm-agent/930\",mountpoint!=\"/var/lib/lxcfs\"}[12h], 3 * 86400) and on (instance) (time() - node_creation_time) > 3600"
    }
   ]
  }
 ]
}